name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing libs
        run: yarn install

      - name: Testing
        run: yarn run jest --ci
